---
- name: create env
  hosts: all
  tasks:
    - name: Add EE to the controller instance
      awx.awx.schedule:
        name: "tt001"
        unified_job_template: "Demo Job Template"
        controller_host: aap-local.lnx.example.local
        controller_password: redhat..123
        controller_username: admin
        organization: Default
        rrule: "DTSTART;TZID=America/Sao_Paulo:20231227T233000 RRULE:INTERVAL=1;FREQ=WEEKLY;BYDAY=TU,WE,TH,FR,SA EXRULE:INTERVAL=1;FREQ=WEEKLY;BYDAY=SU,MO"
        validate_certs: false

