- hosts: localhost  
  connection: local
  tasks:

  - name: login ocp
    ansible.builtin.shell: oc login -u kubeadmin -p "{{ K8S_PASS }}" https://api.upda.sandbox2603.opentlc.com:6443 --insecure-skip-tls-verify=true 
  
  - name: oc get pods
    ansible.builtin.shell: oc get pods -A


  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present



  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: workloads




#  - name: Create fedora virtual machine
#    redhat.openshift_virtualization.kubevirt_vm:
#      api_key: "{{ K8S_AUTH_API_KEY }}"
#      state: present
#      name: fedora-httpd
#      namespace: workloads
#      labels:
#        app: httpd
#      instancetype:
#        name: u1.medium
#      preference:
#        name: fedora
#      spec:
#        domain:
#          devices:
#            interfaces:
#              - name: default
#                masquerade: {}
#        networks:
#          - name: default
#            pod: {}
#        volumes:
#          - containerDisk:
#              image: quay.io/containerdisks/fedora:latest
#            name: containerdisk
#          - cloudInitNoCloud:
#              userData: |-
#                #cloud-config
#                # The default username is: fedora
#            name: cloudinit
  
